name: tpm2
version: 1.0-2
summary: TPM 2.0 utilities
description: |
  Set of utilities and a daemon to deal with TPM 2.0 chips built
  into a wide range of todays devices. Please find the source
  code at: https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/tpm2
confinement: strict

apps:
  resourcemgr:
    command: sbin/resourcemgr
    daemon: simple
    plugs: [tpm, network-bind]
  activatecredential:
    command: sbin/tpm2_activatecredential
    plugs: [network]
  akparse:
    command: sbin/tpm2_akparse
  certify:
    command: sbin/tpm2_certify
    plugs: [network]
  create:
    command: sbin/tpm2_create
    plugs: [network]
  createprimary:
    command: sbin/tpm2_createprimary
    plugs: [network]
  encryptdecrypt:
    command: sbin/tpm2_encryptdecrypt
    plugs: [network]
  evictcontrol:
    command: sbin/tpm2_evictcontrol
    plugs: [network]
  getmanufec:
    command: sbin/tpm2_getmanufec
    plugs: [network]
  getpubak:
    command: sbin/tpm2_getpubak
    plugs: [network]
  getpubek:
    command: sbin/tpm2_getpubek
    plugs: [network]
  getrandom:
    command: sbin/tpm2_getrandom
    plugs: [network]
  hash:
    command: sbin/tpm2_hash
    plugs: [network]
  hmac:
    command: sbin/tpm2_hmac
    plugs: [network]
  listpcrs:
    command: sbin/tpm2_listpcrs
    plugs: [network]
  load:
    command: sbin/tpm2_load
    plugs: [network]
  loadexternal:
    command: sbin/tpm2_loadexternal
    plugs: [network]
  makecredential:
    command: sbin/tpm2_makecredential
    plugs: [network]
  nvdefine:
    command: sbin/tpm2_nvdefine
    plugs: [network]
  nvlist:
    command: sbin/tpm2_nvlist
    plugs: [network]
  nvread:
    command: sbin/tpm2_nvread
    plugs: [network]
  nvrelease:
    command: sbin/tpm2_nvrelease
    plugs: [network]
  nvwrite:
    command: sbin/tpm2_nvwrite
    plugs: [network]
  quote:
    command: sbin/tpm2_quote
    plugs: [network]
  readpublic:
    command: sbin/tpm2_readpublic
    plugs: [network]
  rsadecrypt:
    command: sbin/tpm2_rsadecrypt
    plugs: [network]
  rsaencrypt:
    command: sbin/tpm2_rsaencrypt
    plugs: [network]
  sign:
    command: sbin/tpm2_sign
    plugs: [network]
  takeownership:
    command: sbin/tpm2_takeownership
    plugs: [network]
  unseal:
    command: sbin/tpm2_unseal
    plugs: [network]
  verifysignature:
    command: sbin/tpm2_verifysignature
    plugs: [network]

parts:
  common:
    plugin: dump
    source: .
    snap:
      - copyright.tpm2-tss
      - copyright.tpm2-tools
  tpm2-tss:
    plugin: autotools
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/tpm2
    source-type: git
    source-branch: tpm2-tss/1.0-beta_1
    build-packages:
      - autoconf
      - autoconf-archive
      - libtool
      - gcc
      - g++
      - libc6-dev
    snap:
      - -include
  tpm2-tools:
    plugin: autotools
    #
    # By default the snapcraft autotools plugin doesn't
    # specify the -O2 CFLAG when compiling C/C++.  This
    # causes an undefined symbol when building tpm2_nvlist.
    configflags:
      - "CFLAGS=-O2"
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/tpm2
    source-type: git
    source-branch: tpm2-tools/v1.1-beta_1
    build-packages:
      - autoconf
      - autoconf-archive
      - pkg-config
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
    snap:
      - -include
    after:
      - tpm2-tss
