name: tpm2-simulator
version: 3.1.3-tpm2-tools-1332-ibmswtpm2
summary: TPM 2.0 utilities
description: |
  Set of utilities and a daemon to deal with TPM 2.0.
  Software TPM2 simulator from IBM included.

confinement: strict
grade: stable
base: core18

slots:
  tpm2-abrmd-dbus: # name that is used with 'snap connect' on slots side
    interface: dbus
    bus: system
    name: com.intel.tss2.Tabrmd

apps:
  tpm-server:
    command: sbin/tpm_server
    daemon: simple
    plugs: [tpm, network-bind]
  tpm2-abrmd:
    command: sbin/tpm2-abrmd --allow-root --tcti=mssim
    daemon: simple
    plugs: [tpm, network-bind]
    slots: [tpm2-abrmd-dbus]
  activatecredential:
    command: bin/tpm2_activatecredential
    plugs: [network, home]
  certify:
    command: bin/tpm2_certify
    plugs: [network, home]
  create:
    command: bin/tpm2_create
    plugs: [network, home]
  createpolicy:
    command: bin/tpm2_createpolicy
    plugs: [network, home]
  createprimary:
    command: bin/tpm2_createprimary
    plugs: [network, home]
  dictionarylockout:
    command: bin/tpm2_dictionarylockout
    plugs: [network, home]
  encryptdecrypt:
    command: bin/tpm2_encryptdecrypt
    plugs: [network, home]
  evictcontrol:
    command: bin/tpm2_evictcontrol
    plugs: [network, home]
  getcap:
    command: bin/tpm2_getcap
    plugs: [network, home]
  getmanufec:
    command: bin/tpm2_getmanufec
    plugs: [network, home]
  getpubak:
    command: bin/tpm2_getpubak
    plugs: [network, home]
  getpubek:
    command: bin/tpm2_getpubek
    plugs: [network, home]
  getrandom:
    command: bin/tpm2_getrandom
    plugs: [network, home]
  hash:
    command: bin/tpm2_hash
    plugs: [network, home]
  hmac:
    command: bin/tpm2_hmac
    plugs: [network, home]
  listpersistent:
    command: bin/tpm2_listpersistent
    plugs: [network, home]
  load:
    command: bin/tpm2_load
    plugs: [network, home]
  loadexternal:
    command: bin/tpm2_loadexternal
    plugs: [network, home]
  makecredential:
    command: bin/tpm2_makecredential
    plugs: [network, home]
  nvdefine:
    command: bin/tpm2_nvdefine
    plugs: [network, home]
  nvlist:
    command: bin/tpm2_nvlist
    plugs: [network, home]
  nvread:
    command: bin/tpm2_nvread
    plugs: [network, home]
  nvreadlock:
    command: bin/tpm2_nvreadlock
    plugs: [network, home]
  nvrelease:
    command: bin/tpm2_nvrelease
    plugs: [network, home]
  nvwrite:
    command: bin/tpm2_nvwrite
    plugs: [network, home]
  nvpcrevent:
    command: bin/tpm2_pcrevent
    plugs: [network, home]
  nvpcrextend:
    command: bin/tpm2_pcrextend
    plugs: [network, home]
  nvpcrlist:
    command: bin/tpm2_pcrlist
    plugs: [network, home]
  quote:
    command: bin/tpm2_quote
    plugs: [network, home]
  rc-decode:
    command: bin/tpm2_rc_decode
    plugs: [network, home]
  readpublic:
    command: bin/tpm2_readpublic
    plugs: [network, home]
  rsadecrypt:
    command: bin/tpm2_rsadecrypt
    plugs: [network, home]
  rsaencrypt:
    command: bin/tpm2_rsaencrypt
    plugs: [network, home]
  send:
    command: bin/tpm2_send
    plugs: [network, home]
  sign:
    command: bin/tpm2_sign
    plugs: [network, home]
  startup:
    command: bin/tpm2_startup
    plugs: [network, home]
  takeownership:
    command: bin/tpm2_takeownership
    plugs: [network, home]
  unseal:
    command: bin/tpm2_unseal
    plugs: [network, home]
  verifysignature:
    command: bin/tpm2_verifysignature
    plugs: [network, home]
  tssactivatecredential:
    command: bin/tssactivatecredential
    plugs: [network, home]
  tsscertify:
    command: bin/tsscertify
    plugs: [network, home]
  tsscertifycreation:
    command: bin/tsscertifycreation
    plugs: [network, home]
  tsschangeeps:
    command: bin/tsschangeeps
    plugs: [network, home]
  tsschangepps:
    command: bin/tsschangepps
    plugs: [network, home]
  tssclear:
    command: bin/tssclear
    plugs: [network, home]
  tssclearcontrol:
    command: bin/tssclearcontrol
    plugs: [network, home]
  tssclockrateadjust:
    command: bin/tssclockrateadjust
    plugs: [network, home]
  tssclockset:
    command: bin/tssclockset
    plugs: [network, home]
  tsscommit:
    command: bin/tsscommit
    plugs: [network, home]
  tsscontextload:
    command: bin/tsscontextload
    plugs: [network, home]
  tsscontextsave:
    command: bin/tsscontextsave
    plugs: [network, home]
  tsscreate:
    command: bin/tsscreate
    plugs: [network, home]
  tsscreateek:
    command: bin/tsscreateek
    plugs: [network, home]
  tsscreateekcert:
    command: bin/tsscreateekcert
    plugs: [network, home]
  tsscreateloaded:
    command: bin/tsscreateloaded
    plugs: [network, home]
  tsscreateprimary:
    command: bin/tsscreateprimary
    plugs: [network, home]
  tssdictionaryattacklockreset:
    command: bin/tssdictionaryattacklockreset
    plugs: [network, home]
  tssdictionaryattackparameters:
    command: bin/tssdictionaryattackparameters
    plugs: [network, home]
  tssduplicate:
    command: bin/tssduplicate
    plugs: [network, home]
  tsseccparameters:
    command: bin/tsseccparameters
    plugs: [network, home]
  tssecephemeral:
    command: bin/tssecephemeral
    plugs: [network, home]
  tssencryptdecrypt:
    command: bin/tssencryptdecrypt
    plugs: [network, home]
  tsseventextend:
    command: bin/tsseventextend
    plugs: [network, home]
  tsseventsequencecomplete:
    command: bin/tsseventsequencecomplete
    plugs: [network, home]
  tssevictcontrol:
    command: bin/tssevictcontrol
    plugs: [network, home]
  tssflushcontext:
    command: bin/tssflushcontext
    plugs: [network, home]
  tssgetcapability:
    command: bin/tssgetcapability
    plugs: [network, home]
  tssgetcommandauditdigest:
    command: bin/tssgetcommandauditdigest
    plugs: [network, home]
  tssgetrandom:
    command: bin/tssgetrandom
    plugs: [network, home]
  tssgetsessionauditdigest:
    command: bin/tssgetsessionauditdigest
    plugs: [network, home]
  tssgettestresult:
    command: bin/tssgettestresult
    plugs: [network, home]
  tssgettime:
    command: bin/tssgettime
    plugs: [network, home]
  tsshash:
    command: bin/tsshash
    plugs: [network, home]
  tsshashsequencestart:
    command: bin/tsshashsequencestart
    plugs: [network, home]
  tsshierarchychangeauth:
    command: bin/tsshierarchychangeauth
    plugs: [network, home]
  tsshierarchycontrol:
    command: bin/tsshierarchycontrol
    plugs: [network, home]
  tsshmac:
    command: bin/tsshmac
    plugs: [network, home]
  tsshmacstart:
    command: bin/tsshmacstart
    plugs: [network, home]
  tssimaextend:
    command: bin/tssimaextend
    plugs: [network, home]
  tssimport:
    command: bin/tssimport
    plugs: [network, home]
  tssimportpem:
    command: bin/tssimportpem
    plugs: [network, home]
  tssload:
    command: bin/tssload
    plugs: [network, home]
  tssloadexternal:
    command: bin/tssloadexternal
    plugs: [network, home]
  tssmakecredential:
    command: bin/tssmakecredential
    plugs: [network, home]
  tssntc2getconfig:
    command: bin/tssntc2getconfig
    plugs: [network, home]
  tssntc2lockconfig:
    command: bin/tssntc2lockconfig
    plugs: [network, home]
  tssntc2preconfig:
    command: bin/tssntc2preconfig
    plugs: [network, home]
  tssnvcertify:
    command: bin/tssnvcertify
    plugs: [network, home]
  tssnvchangeauth:
    command: bin/tssnvchangeauth
    plugs: [network, home]
  tssnvdefinespace:
    command: bin/tssnvdefinespace
    plugs: [network, home]
  tssnvextend:
    command: bin/tssnvextend
    plugs: [network, home]
  tssnvglobalwritelock:
    command: bin/tssnvglobalwritelock
    plugs: [network, home]
  tssnvincrement:
    command: bin/tssnvincrement
    plugs: [network, home]
  tssnvread:
    command: bin/tssnvread
    plugs: [network, home]
  tssnvreadlock:
    command: bin/tssnvreadlock
    plugs: [network, home]
  tssnvreadpublic:
    command: bin/tssnvreadpublic
    plugs: [network, home]
  tssnvsetbits:
    command: bin/tssnvsetbits
    plugs: [network, home]
  tssnvundefinespace:
    command: bin/tssnvundefinespace
    plugs: [network, home]
  tssnvundefinespacespecial:
    command: bin/tssnvundefinespacespecial
    plugs: [network, home]
  tssnvwrite:
    command: bin/tssnvwrite
    plugs: [network, home]
  tssnvwritelock:
    command: bin/tssnvwritelock
    plugs: [network, home]
  tssobjectchangeauth:
    command: bin/tssobjectchangeauth
    plugs: [network, home]
  tsspcrallocate:
    command: bin/tsspcrallocate
    plugs: [network, home]
  tsspcrevent:
    command: bin/tsspcrevent
    plugs: [network, home]
  tsspcrextend:
    command: bin/tsspcrextend
    plugs: [network, home]
  tsspcrread:
    command: bin/tsspcrread
    plugs: [network, home]
  tsspcrreset:
    command: bin/tsspcrreset
    plugs: [network, home]
  tsspolicyauthorize:
    command: bin/tsspolicyauthorize
    plugs: [network, home]
  tsspolicyauthorizenv:
    command: bin/tsspolicyauthorizenv
    plugs: [network, home]
  tsspolicyauthvalue:
    command: bin/tsspolicyauthvalue
    plugs: [network, home]
  tsspolicycommandcode:
    command: bin/tsspolicycommandcode
    plugs: [network, home]
  tsspolicycountertimer:
    command: bin/tsspolicycountertimer
    plugs: [network, home]
  tsspolicycphash:
    command: bin/tsspolicycphash
    plugs: [network, home]
  tsspolicyduplicationselect:
    command: bin/tsspolicyduplicationselect
    plugs: [network, home]
  tsspolicygetdigest:
    command: bin/tsspolicygetdigest
    plugs: [network, home]
  tsspolicymaker:
    command: bin/tsspolicymaker
    plugs: [network, home]
  tsspolicymakerpcr:
    command: bin/tsspolicymakerpcr
    plugs: [network, home]
  tsspolicynamehash:
    command: bin/tsspolicynamehash
    plugs: [network, home]
  tsspolicynv:
    command: bin/tsspolicynv
    plugs: [network, home]
  tsspolicynvwritten:
    command: bin/tsspolicynvwritten
    plugs: [network, home]
  tsspolicyor:
    command: bin/tsspolicyor
    plugs: [network, home]
  tsspolicypassword:
    command: bin/tsspolicypassword
    plugs: [network, home]
  tsspolicypcr:
    command: bin/tsspolicypcr
    plugs: [network, home]
  tsspolicyrestart:
    command: bin/tsspolicyrestart
    plugs: [network, home]
  tsspolicysecret:
    command: bin/tsspolicysecret
    plugs: [network, home]
  tsspolicysigned:
    command: bin/tsspolicysigned
    plugs: [network, home]
  tsspolicytemplate:
    command: bin/tsspolicytemplate
    plugs: [network, home]
  tsspolicyticket:
    command: bin/tsspolicyticket
    plugs: [network, home]
  tsspowerup:
    command: bin/tsspowerup
    plugs: [network, home]
  tssquote:
    command: bin/tssquote
    plugs: [network, home]
  tssreadclock:
    command: bin/tssreadclock
    plugs: [network, home]
  tssreadpublic:
    command: bin/tssreadpublic
    plugs: [network, home]
  tssreturncode:
    command: bin/tssreturncode
    plugs: [network, home]
  tssrewrap:
    command: bin/tssrewrap
    plugs: [network, home]
  tssrsadecrypt:
    command: bin/tssrsadecrypt
    plugs: [network, home]
  tssrsaencrypt:
    command: bin/tssrsaencrypt
    plugs: [network, home]
  tsssequencecomplete:
    command: bin/tsssequencecomplete
    plugs: [network, home]
  tsssequenceupdate:
    command: bin/tsssequenceupdate
    plugs: [network, home]
  tsssetprimarypolicy:
    command: bin/tsssetprimarypolicy
    plugs: [network, home]
  tssshutdown:
    command: bin/tssshutdown
    plugs: [network, home]
  tsssign:
    command: bin/tsssign
    plugs: [network, home]
  tsssignapp:
    command: bin/tsssignapp
    plugs: [network, home]
  tssstartauthsession:
    command: bin/tssstartauthsession
    plugs: [network, home]
  tssstartup:
    command: bin/tssstartup
    plugs: [network, home]
  tssstirrandom:
    command: bin/tssstirrandom
    plugs: [network, home]
  tsstimepacket:
    command: bin/tsstimepacket
    plugs: [network, home]
  tsstpm2pem:
    command: bin/tsstpm2pem
    plugs: [network, home]
  tsstpmpublic2eccpoint:
    command: bin/tsstpmpublic2eccpoint
    plugs: [network, home]
  tssunseal:
    command: bin/tssunseal
    plugs: [network, home]
  tssverifysignature:
    command: bin/tssverifysignature
    plugs: [network, home]
  tsswriteapp:
    command: bin/tsswriteapp
    plugs: [network, home]
  tsszgen2phase:
    command: bin/tsszgen2phase
    plugs: [network, home]

parts:
  common:
    plugin: dump
    source: .
    prime:
      - copyright.tpm2-tss
      - copyright.tpm2-tools

  tpm2-tss:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tss.git
    source-type: git
    source-tag: 2.0.1
    configflags:
      - --enable-unit
    build-packages:
      - autoconf
      - autoconf-archive
      - libtool
      - gcc-7
      - g++-7
      #- gcc #16.04
      #- g++ #16.04
      - libc6-dev
      - liburiparser-dev
      - libssl-dev
      - libgcrypt20-dev
    stage-packages:
      - libgcrypt20
      - libssl1.1
      #- libssl1.0.0 #16.04
      - libgpg-error0
    install: |
      # Run all tests shipped by default
      make check -j8

  tpm2-abrmd:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-abrmd.git
    source-type: git
    source-tag: 2.0.3
    configflags:
      - --enable-unit
      - --with-dbuspolicydir=/etc/dbus-1/system.d
    build-packages:
      - libdbus-1-dev
      - libglib2.0-dev
      - dbus-x11
      - wget #16.04
    after:
      - tpm2-tss
    override-build: |
      # workaround 16.04 autoconf-archive https://github.com/tpm2-software/tpm2-abrmd/issues/404
      #sed -i '/AX_VALGRIND_DFLT(\[sgcheck.*/d' configure.ac
      #sed -i '/AX_VALGRIND_DFLT(\[helgrind.*/d' configure.ac
      #sed -i '/AX_VALGRIND_DFLT(\[drd.*/d' configure.ac

      snapcraftctl build

      dbus-launch make check -j8

  tpm2-tools:
    plugin: autotools
    #
    # By default the snapcraft autotools plugin doesn't
    # specify the -O2 CFLAG when compiling C/C++.  This
    # causes an undefined symbol when building tpm2_nvlist.
    #configflags:
    #  - "CFLAGS=-O2"
    source: https://github.com/tpm2-software/tpm2-tools.git
    source-type: git
    source-tag: 3.1.3
    configflags:
      - --enable-unit
    build-packages:
      - pkg-config
      - libcmocka-dev
      - libtool
      - python-pretty-yaml
      #- python-yaml #16.04
      - lcov
      - pandoc
      - libcurl4-openssl-dev
    stage-packages:
      - libgnutls-openssl27
      - openssl
      - libcom-err2
      #- libcomerr2 #16.04
      - libkeyutils1
      - zlib1g
      - libasn1-8-heimdal
      - libcurl4
      #- libcurl3 #16.04
      - libgssapi-krb5-2
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libk5crypto3
      - libkrb5-26-heimdal
      - libkrb5-3
      - libkrb5support0
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      #- libpsl0 #16.04
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsqlite3-0
      - libwind0-heimdal
      - libdb5.3
    after:
      - tpm2-tss
      - tpm2-abrmd
    install: |
      # Run all tests shipped by default
      make check -j8

  ibmtpm20tss:
    plugin: autotools
    source: https://git.code.sf.net/p/ibmtpm20tss/tss
    source-type: git
    source-tag: autotoolsv2
    configflags:
      - --disable-tpm-1.2
    after:
      - tpm2-tools

  ibmswtpm2:
    plugin: make
    source: https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1332.tar.gz
    source-type: tar
    after:
      - ibmtpm20tss
    override-build: |
      cd src
      make -j8
      mkdir -p $SNAPCRAFT_PART_INSTALL/sbin/
      mv tpm_server $SNAPCRAFT_PART_INSTALL/sbin/
